---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyapp
  name: pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyapp
      version: v1
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - image: docker.ntl.nc/pyapp:v1
        name: pyapp
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pyapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: pyapp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pyapp
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: pyapp.nc
    http:
      paths:
      - path: /
        backend:
          serviceName: pyapp
          servicePort: 80
