version: '3.3'

services:

#### Nginx proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - frontend

#### Wordpress
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PassW0rD
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html/wp-content
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PassW0rD
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: wordpress.nc
    networks:
      - frontend
      - backend


#### PyApp
  pyapp:
    image: hello:latest
    restart: always
    volumes:
      - ./hello.py:/hello.py
    environment:
      VIRTUAL_HOST: pyapp.nc
      VIRTUAL_PORT: 5000
    networks:
      - frontend

networks:
  frontend: {}
  backend: {}

volumes:
  db_data: {}
  wp_data: {}
