FROM debian:buster

RUN     mkdir /app && \
        apt-get update && apt-get install -y curl apt-transport-https gnupg2 && \
        curl -sL https://deb.nodesource.com/setup_12.x -o /tmp/nodesource_setup.sh && \
        bash /tmp/nodesource_setup.sh && \
        apt-get -y dist-upgrade && \
        apt-get install -y \
        nodejs \
        npm \
        gconf-service \
        libasound2 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libc6 \
        libcairo2 \
        libcups2  \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgcc1 \
        libgconf-2-4 \
        libgdk-pixbuf2.0-0 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        ca-certificates \
        fonts-liberation \
        libappindicator1 \
        libnss3 \
        lsb-release \
        xdg-utils \
        wget \
        jq \
        libcurl4-gnutls-dev && \
        rm -rf /var/lib/apt/lists/*

ADD app/package.json /app/
ADD app/package-lock.json /app/

WORKDIR /app

RUN npm install

ADD app/index.js /app/
# Compiler assets

CMD npm start
